development:
  adapter: postgresql
  encoding: utf8
  database: json_api
  username: postgres
  password: password

  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: json_api_test
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: json_api_test
  username: postgres
  password: password
